# also change node version in .travis.yml file
FROM node:10-alpine

EXPOSE 5000

ENV HOME=/home/app/
# RUN mkdir -p "$HOME"
WORKDIR $HOME

COPY dist config .env* .sequelizerc package*.json $HOME/
RUN mkdir -p "$HOME" &&\
    npm install --production &&\
    chown -R node:node .

USER node

CMD ["npm", "run", "_production"]
