FROM node:12-alpine

EXPOSE 5000

# USER node
RUN mkdir /home/app
WORKDIR /home/app

EXPOSE 5000

ARG ENV=development
ENV NODE_ENV $ENV

# nodemon to make auto restart node when compiled sources change.
# --enable-source-maps to display .ts files in stacktrace instead of un-helpful transpiled .js files
#    You can also use 'source-map-support' npm package if this built-in node arg doesn't work.
CMD npx nodemon --enable-source-maps dist/app_startup.js

COPY package* ./
# examples don't use package-lock.json to minimize updates 
RUN npm install --no-package-lock 
RUN npm install nodemon
COPY dist ./dist
COPY app ./app