FROM node:6.10.0-alpine

EXPOSE 5000

RUN apk add --update python sqlite sqlite-libs alpine-sdk

ENV HOME=/home/app
RUN addgroup app
RUN adduser -G app -h $HOME -s /bin/false -D app
RUN mkdir -p $HOME/foo-app
WORKDIR $HOME/foo-app

# docker has a cache where as long as files don't change, it caches it.
# So having the bottom two lines here like this, we only run yarn when
# package.json or yarn.lock changes.
COPY package.json package-lock.json $HOME/foo-app/
RUN chown -R app:app .
RUN npm install --production
###########
COPY . $HOME/foo-app/
RUN chown -R app:app .
USER app

RUN npm run build
CMD ["npm", "run", "run-build"]
