FROM node:8-alpine

EXPOSE 5000

ENV HOME=/var/lib/app
RUN mkdir -p "$HOME"
WORKDIR $HOME

COPY . $HOME/
RUN npm install --production &&\
    chown -R node:node . &&\
    npm run production:build

USER node

CMD ["npm", "run", "production:run"]
