# We want this image to be as close to the production image as possible. We copied all the contents of production and put 
# it inside of this file and then added some pieces we needed. 
FROM node:12-alpine 

EXPOSE 5000

ENV HOME=/home/app/
RUN mkdir -p ${HOME}
WORKDIR ${HOME}

ENV NODE_ENV=development

COPY --chown=node:node package*.json ${HOME}/
COPY --chown=node:node dist ${HOME}/dist
COPY --chown=node:node app ${HOME}/app

RUN npm install -g install-subset &&\
    subset install --npm dev_container

# nodemon to make auto restart node when compiled sources change.
# --enable-source-maps to display .ts files in stacktrace instead of un-helpful transpiled .js files
#    You can also use 'source-map-support' npm package if this built-in node arg doesn't work.
CMD npx nodemon --enable-source-maps dist/start.js
